# Generated by Django 3.2.5 on 2021-07-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, verbose_name='Kullanıcı Adı')),
                ('passwd', models.CharField(max_length=100, verbose_name='Şifre')),
            ],
        ),
    ]
