# Generated by Django 3.2.5 on 2021-07-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isloged',
            field=models.BooleanField(default=False, verbose_name='Giriş durumu'),
        ),
    ]
